Rails.application.routes.draw do
  root "dojo#index"
  get "dojos/new" => "dojo#new"
  post "dojos/create" => "dojo#create"
  get "dojos/:id" => "dojo#show"
  get "dojos/:id/edit" => "dojo#edit"
  patch "dojos/:id" => "dojo#update"
  delete "dojos/:id" => "dojo#destroy"
  get "dojos/:id/students/new" => "student#new"
  post "dojos/:id/students" => "student#create"
  get "dojos/:dojo_id/students/:student_id" => "student#show"
  delete "dojos/:dojo_id/students/:student_id" => "student#destroy"
  get "dojos/:dojo_id/students/:student_id/edit" => "student#edit"
  patch "dojos/:dojo_id/students/:student_id" => "student#update"
end
